# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-gist
  - github-pages
  - bourbon
  - jemoji
  - rouge
  - jekyll-redirect-from
  - jekyll-toc

include: ['_pages']

languages: ["es", "en"]

title: "Nahuel Brandán"
meta_title: "Nahuel Brandán | Software Developer"
description: > # this means to ignore newlines until "email:"
    Hola! Soy Nahuel Brandán.
    Soy Desarrollador de Software Backend.
    Especializado en el ecosistema Python,
    con más de 3 años de experiencia.
    Resolutivo. Dedicado. Afortunado.

email: nahuelbrandan123@gmail.com

logo: "/assets/img/logo2.webp"
logo_png: "/assets/img/logo2.png"
float_logo: true

cover: "/assets/img/cover.webp"

name: 'Nahuel Brandán'
author: 'Nahuel Brandán'
author_image: "/assets/img/personal/me_new.webp"

paginate: 5

url: "https://www.nahuelbrandan.com"
baseurl: ""

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    year: 'archive/:year/'
    month: 'archive/:year/:month/'
    tag: 'archive/tag/:name/'
