# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-gist
  - github-pages
  - bourbon
  - jemoji
  - rouge

include: ['_pages']

# Site settings
title: "Nahuel Brandán"
meta_title: "Nahuel Brandán - Portfolio & Blog."
description: > # this means to ignore newlines until "email:"
    Personal website, Con muestra de portfolio & artículos.

email: nahuelbrandan123@gmail.com

# blog logo
logo: "/assets/img/logo.webp"
float_logo: true

# blog cover
cover: "/assets/img/cover.webp"

name: 'Nahuel Brandán'
author: 'Nahuel Brandán'
author_image: "/assets/img/me.webp"

paginate: 5

url: "https://www.nahuelbrandan.com"
baseurl: ""

cv: "https://drive.google.com/file/d/119s_l6mmdmdnJ6-qgtJW92hOrXcJ70QO/view?usp=sharing"

social:
  - icon: linkedin-square
    url: https://www.linkedin.com/in/nahuelbrandan/
    desc: Linkedin

  - icon: github
    url: https://github.com/nahuelbrandan
    desc: Github

  - icon: stack-overflow
    url: https://stackoverflow.com/users/6125910/nahuel-brandan
    desc: Stackoverflow

excerpt_separator: <!-- more -->

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    year: 'archive/:year/'
    month: 'archive/:year/:month/'
    tag: 'archive/tag/:name/'
