# Build settings
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-gist
  - github-pages
  - bourbon
  - jemoji
  - rouge

# Site settings
title: "Nahuel Brandán"
description: > # this means to ignore newlines until "email:"
    Portfolio y personal website.

email: contact@nahuelbrandan.com

# blog logo
logo: "/assets/images/logo.png"
float_logo: true

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Nahuel Brandan'
author: 'Nahuel Brandan'
author_image: "/assets/images/me.jpeg"

site_thumbnail: "/assets/images/informatic.jpg"

paginate: 5

url: "https://www.nahuelbrandan.com" # the base hostname & protocol for your site
baseurl: ""

cv: "https://drive.google.com/file/d/1hop-OzJ9wMZ0w9DACcebRu8PWPLzcmgn/view?usp=sharing"

social:

  - icon: linkedin-square
    url: https://www.linkedin.com/in/nahuelbrandan/
    desc: Linkedin
    share_url:
    share_title:
    share_link:

  - icon: github
    url: https://github.com/nahuelbrandan
    desc: Github
    share_url:
    share_title:
    share_link:

  - icon: stack-overflow
    url: https://stackoverflow.com/users/6125910/nahuel-brandan
    desc: Stackoverflow
    share_url:
    share_title:
    share_link:

excerpt_separator: <!-- more -->

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layouts:
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    year: 'archive/:year/'
    month: 'archive/:year/:month/'
    tag: 'archive/tag/:name/'
