# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Nahuel Brandan"
description: > # this means to ignore newlines until "email:"
    Analista en computación

email: nahuelbrandan123@gmail.com

# blog logo
logo: "/assets/images/logo.png"
float_logo: true 

# blog cover
cover: "/assets/images/cover.jpg"

name: 'Nahuel Brandan'
author: 'Nahuel Brandan'
author_image: "/assets/images/me.png"

paginate: 5

url: "https://nahuelbrandan.github.io" # the base hostname & protocol for your site
baseurl: ""


social:

  - icon: github
    url: https://github.com/nahuelbrandan
    desc: sigueme en github
    share_url:
    share_title:
    share_link:

excerpt_separator: <!-- more -->

jekyll-archives:
  enabled: 
    - year
    - month
    - tags
  layouts: 
    year: year-archive
    month: month-archive
    tag: tag-archive
  permalinks:
    year: 'archive/:year/'
    month: 'archive/:year/:month/'
    tag: 'archive/tag/:name/'
